apiVersion: "nais.io/v1alpha1"
kind: "Application"
webproxy: true
metadata:
  name: pensjon-pol-innsyn
  namespace: {{namespace}}
  labels:
    team: teampeon
spec:
  image: repo.adeo.no:5443/pensjon-pol-innsyn:{{version}}
  port: 8080
  ingresses:
    - {{ingress}}
  liveness:
    path: isAlive
  readiness:
    path: isReady
  vault:
    enabled: true
  replicas:
    min: 1
    max: 1
  resources:
    limits:
      cpu: 1000m
      memory: 512Mi
    requests:
      cpu: 200m
      memory: 256Mi
  prometheus:
    enabled: true
