apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: pensjon-pol-innsyn
  namespace: default
  labels:
    team: pensjonsamhandling
spec:
  image: {{ image }}
  port: 8080
  ingresses:
    - https://pensjon-pol-innsyn.nais.preprod.local
  liveness:
    path: /isAlive
  readiness:
    path: /isReady
  webproxy: true
  vault:
    enabled: true
  replicas:
    min: 1
    max: 1
  resources:
    limits:
      cpu: 1000m
      memory: 512Mi
    requests:
      cpu: 200m
      memory: 256Mi
  prometheus:
    enabled: true
