apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: pensjon-pol-innsyn-popp
  namespace: default
  labels:
    team: pensjonsamhandling
spec:
  image: {{ image }}
  port: 8080
  ingresses:
    - https://pensjon-pol-innsyn-popp.nais.adeo.no
  liveness:
    path: actuator/health/liveness
    initialDelay: 120
    periodSeconds: 1
    failureThreshold: 120
  readiness:
    path: actuator/health/readiness
    initialDelay: 120
    periodSeconds: 1
    failureThreshold: 120
  vault:
    enabled: true
    paths:
      - mountPath: /secrets/oracle/popp
        kvPath: oracle/data/prod/creds/pop_p-user
      - mountPath: /secrets/oracle/config
        kvPath: oracle/data/prod/config/pop_p
  replicas:
    min: 1
    max: 1
  resources:
    limits:
      cpu: 1000m
      memory: 512Mi
    requests:
      cpu: 200m
      memory: 256Mi
  prometheus:
    enabled: true
    path: actuator/prometheus
