apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: pensjon-pol-innsyn-popp
  namespace: default
  labels:
    team: pensjonsamhandling
spec:
  image: {{ image }}
  port: 8080
  ingresses:
    - https://pensjon-pol-innsyn-popp.nais.adeo.no
  liveness:
    path: isAlive
  readiness:
    path: isReady
  vault:
    enabled: true
    paths:
      - mountPath: /secrets/oracle/popp
        kvPath: oracle/data/prod/creds/popp-user
  replicas:
    min: 1
    max: 1
  resources:
    limits:
      cpu: 1000m
      memory: 512Mi
    requests:
      cpu: 200m
      memory: 256Mi
  prometheus:
    enabled: true
