name: Release to GitHub Package Registry

on:
  push:
    branches: master

jobs:
  build_and_release:
    permissions:
      contents: "read"
      id-token: "write"  
    name: 'Build and release'
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout repository'
        uses: actions/checkout@v4

      - name: 'Java'
        uses: actions/setup-java@v4
        with:
          java-version: '15.x'
          distribution: 'temurin'

      - name: 'Build'
        run: gradle clean build

      - name: 'Build and push docker image'
        uses: nais/docker-build-push@v0
        id: docker-push
        with:
          team: pensjonopptjening
          tag: ${{ github.sha }}

      - name: 'Deploy to dev-fss'
        uses: nais/deploy/actions/deploy@v2
        env:
          CLUSTER: dev-fss
          RESOURCE: .nais/nais-dev.yaml
          IMAGE: ${{ steps.docker-push.outputs.image }}
          TELEMETRY: ${{ steps.docker-push.outputs.telemetry }}

      - name: 'Deploy to prod-fss'
        uses: nais/deploy/actions/deploy@v2
        env:
          CLUSTER: prod-fss
          RESOURCE: .nais/nais-prod.yaml
          IMAGE: ${{ steps.docker-push.outputs.image }}
          TELEMETRY: ${{ steps.docker-push.outputs.telemetry }}
